<?php

// autoload.php @generated by Composer

//require_once __DIR__ . '/composer/autoload_real.php';
require_once 'composer/autoload_real.php';

return ComposerAutoloaderInit34f9ca802e2de6f200b2dda8f00ce2db::getLoader();
